const fs = require('fs');
const path = require('path');

const bankRaw = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'public', 'data', 'pruebas', 'modulo-1-cardiologia.json'), 'utf8'));
const questionBank = Array.isArray(bankRaw) ? bankRaw : (bankRaw.pruebas || []);
const onlineClasses = JSON.parse(fs.readFileSync(path.join(__dirname, 'cardio_online_classes.json'), 'utf8'));

console.log('Total bank questions loaded:', questionBank.length);

// Custom high-yield clinical vignettes and explanations for topics 15 to 47
const customVignettesMap = {
  15: {
    vignette: "Hombre de 64 años, diabético e hipertenso, consulta por dolor retroesternal opresivo de 3 meses de evolución que se desencadena al caminar 2 cuadras o subir escaleras y cede tras 5 minutos de reposo. ECG de reposo es normal. Test de esfuerzo muestra infradesnivel del segmento ST de 2 mm en V4-V6 a los 6 minutos de ejercicio.",
    explicacion: "En la Angina Estable Crónica, la clínica clásica es el dolor torácico opresivo de esfuerzo aliviado por el reposo o nitroglicerina sublingual. El diagnóstico de confirmación inicial se realiza con pruebas de provocación de isquemia (Test de Esfuerzo). El tratamiento médico de primera línea para reducir mortalidad y eventos cardiovasculares incluye Aspirina 100 mg/día, Estatinas a dosis altas (Atorvastatina 80 mg) y Betabloqueadores (Bisoprolol/Atenolol) como antianginoso sintomático. La coronariografía se reserva para pacientes con test de esfuerzo de alto riesgo o síntomas refractarios al tratamiento médico óptimo."
  },
  16: {
    vignette: "Hombre de 58 años es traído al servicio de urgencias por dolor torácico súbito e intenso de 45 minutos de duración. El médico de turno debe descartar de inmediato las 5 causas de dolor torácico que comprometen la vida del paciente.",
    explicacion: "Frente a un dolor torácico agudo en urgencias, la primera medida obligatoria es tomar un Electrocardiograma de 12 derivaciones en menos de 10 minutos desde el ingreso para diagnosticar o descartar un Síndrome Coronario Agudo con supradesnivel ST. La evaluación clínica rápida debe descartar de forma sistemática las 5 patologías torácicas de alta letalidad: 1) Síndrome Coronario Agudo; 2) Disección Aórtica (dolor lacerante hacia la espalda, asimetría de pulsos); 3) Tromboembolismo Pulmonar (disnea brusca, pleurítico, signos de TVP); 4) Neumotórax a Tensión (asimetría ventilatoria, timpanismo); y 5) Rotura Esofágica / Síndrome de Boerhaave (vómitos violentos previos, enfisema subcutáneo)."
  },
  17: {
    vignette: "Hombre de 62 años consulta en urgencias por dolor torácico opresivo de 2 horas de evolución irradiado a mandíbula. El ECG de 12 derivaciones muestra elevación del segmento ST de 3 mm en las derivaciones DII, DIII y aVF, con infradesnivel especular en DI y aVL.",
    explicacion: "El hallazgo electrocardiográfico de supradesnivel del segmento ST ≥ 1 mm en dos o más derivaciones contiguas (o ≥ 2 mm en V2-V3) confirma el diagnóstico de IAM con Supradesnivel de ST (IAMSDST), lo que indica oclusión coronaria transmural completa. La pared inferior se evalúa en DII, DIII y aVF (arteria coronaria derecha o circunfleja). Ante un IAMSDST de pared inferior, es obligatorio tomar derivaciones derechas (V3R y V4R) para descartar compromiso del ventrículo derecho. La conducta prioritaria es la reperfusión miocárdica inmediata (Angioplastia Primaria si se realiza en <120 minutos, o Fibrinólisis si el tiempo de traslado excede las 2 horas)."
  },
  18: {
    vignette: "Mujer de 70 años con antecedentes de hipertensión arterial consulta por disnea súbita y malestar epigástrico de 3 horas de evolución. No refiere dolor torácico típico. Se sospecha equivalente anginoso.",
    explicacion: "En adultos mayores, mujeres y pacientes diabéticos, el Síndrome Coronario Agudo suele presentarse con síntomas atípicos o 'equivalentes anginosos' (disnea aguda, diaforesis, epigastralgia o confusión). Las Troponinas Cardiacas I o T ultrasensibles son los biomarcadores de elección por su elevada sensibilidad y especificidad miocárdica. Se debe realizar una curva de troponinas a las 0 y 3 horas. Para la detección de reinfarto precoz (dentro de los primeros 14 días post-IAM), la Troponina permanece elevada hasta 10-14 días, por lo que la CK-MB (que se normaliza a las 48-72 horas) es el marcador útil para diagnosticar isquemia recurrente."
  },
  19: {
    vignette: "Hombre de 55 años, fumador, consulta por dolor opresivo retroesternal intenso en reposo de 1 hora de duración. El ECG muestra infradesnivel del segmento ST de 2 mm en derivaciones V2-V5. Troponina I resulta marcadamente elevada.",
    explicacion: "El Síndrome Coronario Agudo Sin Supradesnivel de ST (IAMSEST / Angina Inestable) se debe a la fisura o erosión de una placa de ateroma con trombosis parcial no oclusiva. El manejo farmacológico inmediato de primera línea incluye: 1) Antiagregación Plaquetaria Dual (Aspirina 300 mg dosis de carga + Ticagrelor 180 mg o Clopidogrel 300 mg); 2) Anticoagulación parenteral (Heparina de Bajo Peso Molecular - Enoxaparina 1 mg/kg c/12h); 3) Nitroglicerina sublingual/EV para alivio sintomático; 4) Betabloqueadores EV/oral; y 5) Estatinas a dosis altas. Se realiza estratificación de riesgo (escala GRACE/TIMI) para definir la coronariografía de urgencia o precoz (<24h)."
  },
  20: {
    vignette: "Hombre de 68 años, al 4° día post-IAM anterior extenso de pared anterior, presenta bruscamente disnea severa, cianosis y shock. Al examen físico destaca soplo holosistólico en foco mitral IV/VI de reciente aparición, irradiado a la axila, con rales crepitantes difusos en ambos campos pulmonares.",
    explicacion: "Las complicaciones mecánicas del infarto miocárdico agudo ocurren típicamente entre el 3° y 7° día post-IAM. La Rotura de Músculo Papilar (generalmente posteromedial en IAM inferior o anterolateral en IAM anterior) causa una Insuficiencia Mitral Aguda masiva y edema pulmonar agudo cardiogénico severo ('flash'), manifestándose por un soplo holosistólico nuevo en el apex. La Rotura de Pared Libre provoca taponamiento cardíaco súbito con disociación electromecánica. La Comunicación Interventricular (CIV post-IAM) produce un soplo holosistólico en borde esternal izquierdo bajo con frémito. El manejo de todas las complicaciones mecánicas es la estabilización con balón de contrapulsación intraaórtico y Cirugía Cardíaca de Urgencia inmediata."
  },
  21: {
    vignette: "Paciente de 60 años en su 2° día de evolución de un IAM de pared anterior. En el monitor electrocardiográfico continuo presenta ráfagas de extrasístoles ventriculares frecuentes y monomórficas, manteniéndose hemodinámicamente estable.",
    explicacion: "Las arritmias son la complicación más frecuente en la fase aguda del infarto miocárdico. Las Extrasístoles Ventriculares son extremadamente comunes tras un IAM debido al automatismo aumentado del tejido isquémico periinfarto; si el paciente está asintomático y hemodinámicamente estable, NO requieren tratamiento antiarrítmico farmacológico específico (el uso profiláctico de antiarrítmicos aumenta la mortalidad). En cambio, si se desencadena Fibrilación Ventricular (FV primaria) o Taquicardia Ventricular inestable, la desfibrilación/cardioversión eléctrica inmediata es mandatoria. En bloqueos AV en IAM inferior (isquemia nodal reversible), el tratamiento es Atropina 1 mg EV; en IAM anterior extenso (necrosis infranodal de ramas), se requiere Marcapaso Transitorio."
  },
  22: {
    vignette: "Hombre de 66 años ingresa por IAMSDST de pared inferior (supradesnivel ST en DII, DIII, aVF). Presenta PA 80/40 mmHg, FC 55 lpm, ingurgitación yugular marcada hasta el ángulo de la mandíbula, pero auscultación pulmonar completamente limpia sin crepitantes.",
    explicacion: "La tríada clásica del IAM del Ventrículo Derecho incluye: 1) Hipotensión arterial; 2) Ingurgitación yugular (signos de falla derecha); y 3) Campos pulmonares limpios (sin congestión izquierda), asociada a IAM de pared inferior. El diagnóstico se confirma mediante supradesnivel de ST ≥ 1 mm en derivaciones derechas (V3R y V4R). La conducta terapéutica de primera línea es la Sobrecarga de Volumen precavida con Suero Fisiológico EV para optimizar la precarga del VD. Están estrictamente CONTRAINDICADOS los vasodilatadores (Nitratos, Morfina, IECA) y los Diuréticos, ya que al reducir la precarga provocan colapso hemodinámico profundo y shock cardiogénico."
  },
  23: {
    vignette: "Mujer de 72 años con antecedentes de HTA y diabetes consulta por disnea progresiva de esfuerzo (CF III), ortopnea de 2 almohadas y edema de extremidades inferiores. Al examen destaca reflujo hepatoyugular, crépitos basales bilaterales y tercer ruido cardíaco (R3).",
    explicacion: "El diagnóstico de Insuficiencia Cardíaca (IC) es fundamentalmente clínico y se establece mediante los Criterios de Framingham (requiere 2 criterios mayores o 1 mayor + 2 menores). Criterios mayores incluyen: disnea paroxística nocturna, ortopnea, ingurgitación yugular, rales crepitantes, cardiomegalia, edema agudo pulmonar, R3 y reflujo hepatoyugular. El péptido natriurético (BNP / NT-proBNP) tiene un alto valor predictivo negativo para descartar IC en urgencias. El ecocardiograma Doppler es el examen de elección para clasificar la IC según la Fracción de Eyección del Ventrículo Izquierdo: reducida (FEVI ≤ 40%), levemente reducida (FEVI 41-49%) o preservada (FEVI ≥ 50%)."
  },
  24: {
    vignette: "Hombre de 65 años con insuficiencia cardíaca crónica y FEVI 30% sintomático en CF II a pesar de enalapril y carvedilol. Se decide optimizar el tratamiento médico guiado por las guías clínicas GES/MINSAL y guías internacionales.",
    explicacion: "El pilar fundamental del tratamiento farmacológico de la Insuficiencia Cardíaca con FEVI Reducida (FEVI ≤ 40%) se basa en los 4 fármacos modificadores de enfermedad que reducen la mortalidad hospitalaria y cardiovascular ('El Cuadriplete Fantástico'): 1) iSGLT2 (Dapagliflozina 10 mg o Empagliflozina 10 mg/día); 2) ARNI (Sacubitril/Valsartán) en reemplazo de IECA/ARA-II; 3) Betabloqueadores de demostrada eficacia en IC (Carvedilol, Bisoprolol o Metoprolol Succinato); y 4) Antagonistas del Receptor de Mineralocorticoide (Espironolactona 25 mg/día). Los diuréticos de asa (Furosemida) se utilizan exclusivamente a la menor dosis efectiva para aliviar los síntomas de congestión hídrica, pero no reducen la mortalidad a largo plazo."
  },
  25: {
    vignette: "Paciente de 58 años, hipertenso, dislipidémico y fumador activo, evaluado en control ambulatorio post-evento coronario agudo. Presenta dudas sobre los objetivos terapéuticos y metas de prevención secundaria.",
    explicacion: "En pacientes con Cardiopatía Coronaria establecida (prevención secundaria de muy alto riesgo cardiovascular), la estrategia terapéutica integral incluye: 1) Antiagregación plaquetaria permanente (Aspirina 100 mg/día); 2) Metas estrictas de Colesterol LDL < 55 mg/dL (y reducción ≥50% del valor basal) mediante Estatinas de alta potencia (Atorvastatina 80 mg o Rosuvastatina 20-40 mg) asociadas a Ezetimiba si no se alcanza la meta; 3) Control riguroso de la Presión Arterial < 130/80 mmHg mediante IECA/ARA-II; 4) Abandono absoluto del tabaco; y 5) Actividad física aeróbica regular de 150 min/semana."
  },
  26: {
    vignette: "Hombre de 68 años con antecedentes de EPOC severo por tabaquismo de larga data presenta disnea progresiva, aumento de volumen abdominal y edema blando en ambas extremidades inferiores. Al examen destaca cianosis central, ingurgitación yugular con onda 'v' gigante, latido sagital en borde esternal izquierdo y soplo holosistólico que aumenta con la inspiración en foco tricúspide.",
    explicacion: "El Cor Pulmonale se define como la alteración en la estructura y/o función del Ventrículo Derecho (hipertrofia y dilatación) causada por Hipertensión Arterial Pulmonar primaria resultante de enfermedades vasculares o del parénquima pulmonar (siendo el EPOC la causa más frecuente). Clínicamente se presenta con signos de insuficiencia cardíaca derecha pura (edema de EEII, hepatomegalia congestiva tender, ascitis, ingurgitación yugular) en ausencia de insuficiencia ventricular izquierda. El tratamiento definitivo se orienta a la patología pulmonar subyacente (oxigenoterapia domiciliaria continua en EPOC con PaO₂ < 55 mmHg, broncodilatadores) y diuréticos a dosis moderadas para el manejo sintomático de la sobrecarga de volumen."
  },
  27: {
    vignette: "Médico de APS evalúa a un paciente con hallazgo de soplo cardíaco durante el examen físico de rutina. Debe precisar las características semiológicas clave para diferenciar soplos funcionales de soplos orgánicos de alta sospecha de valvulopatía.",
    explicacion: "En la evaluación semiológica de las valvulopatías, los soplos diastólicos (como el de Estenosis Mitral o Insuficiencia Aórtica) y los soplos holosistólicos o continuos son SIEMPRE patológicos y requieren estudio ecocardiográfico. En contraste, los soplos sistólicos eyectivos suaves (Intensidad I-II/VI), sin irradiación, que varían con los cambios de posición y se presentan en pacientes jóvenes asintomáticos suelen corresponder a soplos inocentes o funcionales. La prueba diagnóstica de elección confirmatoria, cuantitativa y anatómica para cualquier valvulopatía es el Ecocardiograma Doppler transtorácico."
  },
  28: {
    vignette: "Hombre de 76 años consulta por episodios recurrentes de síncope al subir escaleras y angina de esfuerzo. Al examen cardíaco se ausculta un soplo sistólico eyectivo rudo, de timbre áspero, en 2° espacio intercostal derecho (foco aórtico), irradiado a ambas arterias carótidas, acompañado de un pulso arterial parvus et tardus.",
    explicacion: "La Estenosis Aórtica Severa es la valvulopatía sintomática más frecuente en el adulto mayor (secundaria a calcificación degenerativa senil). Se manifiesta por la tríada clásica de presentación: 1) Angina de esfuerzo; 2) Síncope de ejercicio; y 3) Disnea / Insuficiencia cardíaca. Al examen físico destaca el soplo sistólico eyectivo cresc-decresc en foco aórtico irradiado a carótidas, el segundo ruido aórtico (A2) disminuido o ausente y el pulso arterial de pequeña amplitud y ascenso lento (pulso parvus et tardus). Una vez que la estenosis aórtica severa se vuelve sintomática, la supervivencia media sin tratamiento es menor a 2-3 años. La indicación terapéutica definitiva es el Reemplazo Valvular Aórtico (quirúrgico o vía percutánea TAVI)."
  },
  29: {
    vignette: "Mujer de 45 años consulta por fatiga y disnea progresiva. Presenta antecedente de soplos en la infancia y fibrilación auricular reciente. Al examen cardiovascular se ausculta chasquido de apertura seguido de un retumbo diastólico de tono grave con reforzamiento presistólico en el apex cardíaco (foco mitral).",
    explicacion: "La Estenosis Mitral se debe casi de forma exclusiva a Secuela de Fiebre Reumática. Su fisiopatología se caracteriza por la obstrucción al flujo desde la aurícula izquierda hacia el ventrículo izquierdo durante la diástole, lo que provoca dilatación auricular izquierda progresiva, hipertensión venocapilar pulmonar (disnea, hemoptisis) y elevada predisposición a Fibrilación Auricular y tromboembolismos sistémicos. El signo auscultatorio patognomónico es el chasquido de apertura seguido del retumbo diastólico en el apex. El tratamiento médico incluye control de frecuencia y anticoagulación permanente en FA; el tratamiento intervencional de elección en anatomía favorable (score de Wilkins ≤ 8) es la Valvuloplastía Mitral Percutánea con Balón."
  },
  30: {
    vignette: "Joven deportista de 22 años sufre pérdida brusca de conciencia durante un partido de fútbol. En la historia familiar refiere que un hermano falleció súbitamente a los 19 años. El ecocardiograma muestra hipertrofia asimétrica del tabique interventricular de 22 mm con gradiente dinámico en el tracto de salida del VI.",
    explicacion: "La Miocardiopatía Hipertrófica (MCH) es una enfermedad genética autosómica dominante (mutación en proteínas del sarcómero) y constituye la causa más frecuente de Muerte Súbita en atletas y adultos jóvenes. Se caracteriza por hipertrofia ventricular izquierda asimétrica (predominio septal) en ausencia de causas secundarias de sobrecarga (como HTA o estenosis aórtica). Al examen destaca un soplo sistólico eyectivo en borde esternal izquierdo que AUMENTA con las maniobras que reducen la precarga (Valsalva, bipedestación) y disminuye con el acuclillamiento. El tratamiento farmacológico inicial son los Betabloqueadores (o Verapamilo); en pacientes con criterios de alto riesgo de muerte súbita se indica la implantación de un Desfibrilador Automático Implantable (DAI)."
  },
  31: {
    vignette: "Mujer de 38 años sin antecedentes cardiovasculares ingresa por un accidente cerebrovascular isquémico agudo en territorio de la arteria cerebral media. El Doppler carotídeo y Holter de ritmo de 24h son normales. El ecocardiograma transesofágico con microburbujas demuestra paso precoz de burbujas de aurícula derecha a izquierda tras maniobra de Valsalva.",
    explicacion: "El Foramen Oval Permeable (FOP) es una anomalía congénita interauricular presente en cerca del 20-25% de la población general. Si bien suele ser asintomático, es la causa principal de Embolía Paradojal en adultos jóvenes con ACV isquémico de origen criptogénico (un trombo venoso originado en extremidades inferiores pasa a la circulación izquierda a través del FOP durante aumentos transitorios de presión en AD). En pacientes jóvenes (<60 años) con ACV criptogénico y FOP de alto riesgo (con aneurisma del septum interauricular), la conducta terapéutica recomendada es el Cierre Percutáneo del FOP con dispositivo Amplatzer asociado a antiagregación plaquetaria."
  },
  32: {
    vignette: "Escolar de 8 años es evaluado en control de niño sano. El examen físico es completamente normal, normotenso, desarrollo pondoestatural adecuado. En la auscultación cardíaca se detecta soplo sistólico Grado II/VI en 2° espacio intercostal izquierdo, suave, de timbre musical, que disminuye en intensidad al sentarse.",
    explicacion: "Los soplos funcionales o inocentes son extremadamente frecuentes en la infancia y adolescencia (presentes en más del 50% de los niños en algún momento). Se caracterizan por: 1) Intensidad leve (Grado I-II/VI); 2) Ocurrencia exclusivamente proto-mesosistólica; 3) Ausencia de síntomas cardiovasculares o cardiomegalia; 4) Variación marcada con la postura o la fase respiratoria; y 5) Ruidos cardíacos R1 y R2 completamente normales sin chasquidos ni clicks. El manejo del soplo inocente en el paciente asintomático consiste en la tranquilidad a los padres y no requiere restricción de actividad física ni seguimiento con ecocardiograma."
  },
  33: {
    vignette: "Hombre de 42 años consulta por dolor torácico retroesternal punzante de 2 días de evolución, de intensidad 8/10, que aumenta marcadamente con la inspiración profunda y al decúbito dorsal, y se alivia al inclinarse hacia adelante. El ECG muestra supradesnivel del ST difuso de concavidad superior en casi todas las derivaciones con infradesnivel del segmento PR.",
    explicacion: "La Pericarditis Aguda es la inflamación del pericardio (causa más frecuente idiopática/viral por Coxsackie o Echovirus). Se diagnostica clínicamente por la presencia de al menos 2 de los 4 criterios: 1) Dolor torácico pleurítico posture-dependiente (alivia al inclinarse hacia adelante - posición mahometana); 2) Frote pericárdico auscultatorio; 3) ECG característico con supradesnivel ST cóncavo difuso ('en guirnalda') e infradesnivel del PR; y 4) Derrame pericárdico nuevo en ecocardiograma. El tratamiento farmacológico de primera línea es la combinación de AINEs a dosis altas (Ibuprofeno 600-800 mg c/8h o Aspirina) más Colchicina 0.5 mg/día durante 3 meses (esta última reduce drásticamente las recurrencias)."
  },
  34: {
    vignette: "Joven de 26 años, sin antecedentes de importancia, ingresa por disnea progresiva, palpitaciones y astenia severa 10 días después de un cuadro febril gripal. El ECG muestra taquicardia sinusal con bloqueos de rama y elevación de troponinas T. El ecocardiograma evidencia disfunción sistólica global del VI con FEVI 32%.",
    explicacion: "La Miocarditis Aguda es la inflamación del miocardio, producida principalmente por infecciones virales (Enterovirus, Adenovirus, Parvovirus B19, SARS-CoV-2). Se presenta clínicamente como un espectro que varía desde dolor torácico de tipo coronario con troponinas elevadas hasta insuficiencia cardíaca aguda de rápida progresión, arritmias ventriculares o shock cardiogénico fulminante en un paciente joven tras un pródromo viral. La Resonancia Magnética Cardíaca (RMC) es la técnica de imagen no invasiva de elección (criterios de Lake Louise). El tratamiento se basa en la terapia estándar de insuficiencia cardíaca, reposo deportivo estricto por 3-6 meses y soporte hemodinámico si evoluciona a shock."
  },
  35: {
    vignette: "Escolar de 11 años consulta por fiebre, inflamación articular migratoria de rodillas y tobillos, y nódulos subcutáneos indoloros en codos. Refiere antecedente de odinofagia febril no tratada hace 3 semanas. Al examen se ausculta un soplo holosistólico apical de insuficiencia mitral de reciente aparición.",
    explicacion: "La Fiebre Reumática Aguda es una complicación inflamatoria autoinmune no supurativa desencadenada por una faringoamigdalitis por Estreptococo Beta-Hemolítico del Grupo A (Streptococcus pyogenes). El diagnóstico se confirma mediante los Criterios de Jones revisados (2 criterios mayores, o 1 mayor + 2 menores, más evidencia de infección estreptocócica previa por ASO o cultivo). Criterios mayores: Carditis (valvulitis mitral/aórtica), Poliartritis migratoria, Corea de Sydenham, Eritema marginado y Nódulos subcutáneos (nemotecnia CANCER). El pilar del tratamiento incluye Penicilina Benzatina dosis única para erradicación estreptocócica, AINEs para la artritis y Profilaxis Secundaria continua con Penicilina Benzatina IM cada 3-4 semanas para prevenir carditis reumática permanente."
  },
  36: {
    vignette: "Hombre de 70 años, internado en la UCI tras una cirugía abdominal mayor, presenta hipotensión (PA 75/40 mmHg), oliguria, frialdad distal, llenado capilar de 5 segundos, lactato sérico de 6.5 mmol/L y Saturación Venosa Central de O₂ de 52%.",
    explicacion: "El Shock es un estado de colapso circulatorio caracterizado por la perfusión tisular inadecuada e hipoxia celular sistémica. Se clasifica hemodinámicamente en 4 tipos principales: 1) Shock Hipovolémico (disminución de precarga por hemorragia o deshidratación); 2) Shock Cardiogénico (fallo de bomba miocárdica con GC bajo y PCOP elevada); 3) Shock Distributivo (Séptico, Anafiláctico, Neurogénico: caracterizado por vasodilatación sistémica severa con RVS marcadamente disminuidas y GC inicial normal/alto); y 4) Shock Obstructivo (obstrucción mecánica al llenado o vaciado cardíaco: TEP masivo, Taponamiento pericárdico, Neumotórax a tensión). El manejo inicial requiere reanimación con fluidos, vasopresores (Norepinefrina de primera línea) y corrección inmediata de la etiología subyacente."
  },
  37: {
    vignette: "Lactante de 4 meses es llevado a control de salud. La madre refiere que se cansa al mamar y presenta sudoración profusa en la frente durante las tomas. Al examen se detecta soplo holosistólico de alta frecuencia e intensidad IV/VI en el 3er-4° espacio intercostal izquierdo con frémito palpar. Los pulsos femorales son simétricos.",
    explicacion: "La Comunicación Interventricular (CIV) es la cardiopatía congénita más frecuente al nacimiento (excluyendo la válvula aórtica bicúspide). Pertenece al grupo de cardiopatías congénitas acianóticas con cortocircuito (shunt) de izquierda a derecha. Clínicamente, las CIV pequeñas (Restrictivas / Mal de Roger) presentan un soplo holosistólico rudo e intenso pero son asintomáticas. Las CIV medianas a grandes producen sobrecarga de volumen en circulación pulmonar e insuficiencia cardíaca del lactante (dificultad alimentaria, diaforesis, escaso incremento ponderal) a partir de las 4-8 semanas de vida a medida que cae la resistencia vascular pulmonar. Si no se corrige a tiempo, evoluciona a hipertensión pulmonar irreversible con inversión del shunt (Síndrome de Eisenmenger)."
  },
  38: {
    vignette: "Recién nacido a término presenta cianosis central generalizada que no responde a la administración de oxígeno al 100% (test de hiperoxia negativo). En la auscultación cardíaca se aprecia segundo ruido único e intenso sin soplos significativos. La radiografía de tórax muestra una silueta cardíaca en forma de 'huevo en un hilo'.",
    explicacion: "En la semiología de las Cardiopatías Congénitas, la presencia de Cianosis precoz al nacer orienta a lesiones con cortocircuito de derecha a izquierda (Cardiopatías Cianóticas). La Transposición de Grandes Arterias (TGA) es la causa más frecuente de cianosis neonatal en las primeras 24 horas de vida; la Tetralogía de Fallot (Estenosis pulmonar, CIV, Apercibimiento aórtico e Hipertrofia VD) es la causa cianótica más frecuente pasada la etapa neonatal (radiografía en 'zueco' o 'bota'). Ante la sospecha de cardiopatía cianótica ductus-dependiente en un recién nacido con hipotensión o cianosis severa, la medida terapéutica inmediata de rescate antes del traslado quirúrgico es la infusión continua de Prostaglandina E1 (Alprostadil) para mantener abierto el conducto arterioso."
  },
  39: {
    vignette: "Hombre de 60 años con antecedente de hipertensión arterial no controlada ingresa por dolor torácico súbito, de intensidad máxima desde el inicio (10/10), de carácter desgarrador o lacerante, irradiado a la región interescapular. Al examen físico destaca PA 190/110 en brazo derecho y 130/70 en brazo izquierdo, con soplito de insuficiencia aórtica nuevo.",
    explicacion: "La Disección Aórtica es una emergencia cardiovascular catastrófica provocada por el desgarro de la túnica íntima aórtica. El síntoma cardinal es el dolor torácico transfixiante agudo máximo desde el comienzo irradiado a la espalda. La presencia de asimetría de presiones arteriales entre ambos brazos (>20 mmHg) o pulso asimétrico apoya fuertemente el diagnóstico. Se clasifica según Stanford en: Tipo A (compromete la aorta ascendente; requiere Cirugía Quirúrgica de Urgencia inmediata por alto riesgo de rotura, taponamiento o insuficiencia aórtica) y Tipo B (compromete solo aorta descendente distal a la subclavia izquierda; manejo médico de entrada con Betabloqueadores EV como Esmolol/Labetalol para controlar PA < 120/80 y dP/dt)."
  },
  40: {
    vignette: "Hombre de 72 años, fumador e hipertenso, es evaluado en urgencias por dolor lumbosacro sordo. Durante la palpación abdominal profunda se detecta una masa pulsátil expansiva e indolora en el epigastrio e hipocondrio izquierdo. El ecofast abdominal muestra un diámetro aórtico infrarrenal de 5.8 cm.",
    explicacion: "El Aneurisma de Aorta Abdominal (AAA) se define como la dilatación localizada de la aorta abdominal mayor a 3.0 cm de diámetro (siendo el segmento infrarrenal la localización más frecuente). El factor de riesgo modificable más importante es el tabaquismo. La mayoría de los AAA son asintomáticos y se diagnostican incidentalmente en ecografías. El riesgo de rotura catastrófica aumenta exponencialmente con diámetros ≥ 5.5 cm en hombres (o ≥ 5.0 cm en mujeres) o un crecimiento rápido >0.5 cm en 6 meses. Las indicaciones de reparación electiva (mediante reparación endovascular EVAR o cirugía abierta) son: diámetro ≥ 5.5 cm o aneurismas sintomáticos/dolorosos independientemente de su tamaño."
  },
  41: {
    vignette: "Mujer de 74 años con fibrilación auricular no anticoagulada presenta dolor súbito e insoportable en la pierna derecha de 3 horas de evolución. Al examen físico, la extremidad inferior derecha se aprecia pálida, fría al tacto desde la rodilla hacia distal, con ausencia completa de pulsos poplíteo, tibial posterior y pedio. Presenta parestesias y disminución de la fuerza muscular de los dedos.",
    explicacion: "La Isquemia Aguda de Extremidades Inferiores es una emergencia vascular súbita provocada por la oclusión arterial brusca (siendo la Embolía de origen cardíaco por Fibrilación Auricular la causa más frecuente, seguida de la trombosis in situ). Se manifiesta clínicamente por las '6 P de Pratt': 1) Pain (Dolor súbito); 2) Pallor (Palidez); 3) Pulselessness (Ausencia de pulsos); 4) Paresthesia (Parestesias); 5) Paralysis (Parálisis muscular); y 6) Poikilothermia (Frialdad). Ante una extremidad viables o amenazada (Grado I-II), se debe iniciar anticoagulación inmediata con bolo de Heparina No Fraccionada EV y revascularización de urgencia mediante Trombectomía Quirúrgica con Catéter de Fogarty o fibrinólisis intraarterial antes de las 6 horas para evitar la amputación irrecuperable."
  },
  42: {
    vignette: "Hombre de 67 años, diabético y fumador, consulta por dolor muscular tipo calambre en la pantorrilla derecha que aparece invariablemente al caminar 150 metros y lo obliga a detenerse; el dolor cede por completo tras 3-5 minutos de reposo. Al examen, la piel de los pies está atrófica y el Índice Tobillo-Brazo (ITB) derecho es de 0.62.",
    explicacion: "La Isquemia Crónica de Extremidades Inferiores (Enfermedad Arterial Periférica) se debe a la ateroesclerosis progresiva de las arterias de los miembros inferiores. El síntoma cardinal es la Claudicación Intermitente (dolor muscular desencadenado por el ejercicio y aliviado por el reposo). El diagnóstico confirmatorio inicial no invasivo de elección es el Índice Tobillo-Brazo (ITB); un valor de ITB ≤ 0.90 confirma la presencia de enfermedad arterial periférica (ITB < 0.40 indica isquemia crítica). El tratamiento conservador de primera línea incluye: cese tabáquico estricto, programa de caminata estructurada, Aspirina 100 mg/día, Estatinas a dosis altas y Cilostazol 100 mg c/12h para mejorar la distancia de caminata."
  },
  43: {
    vignette: "Hombre de 71 años consulta tras presentar un episodio transitorio de pérdida de visión monocular en el ojo izquierdo de 10 minutos de duración (amaurosis fugaz), seguido de debilidad en la mano derecha que recuperó totalmente en 30 minutos. El Eco-Doppler Carotídeo revela una estenosis del 82% en la arteria carótida interna izquierda por placa ateromatosa ulcerada.",
    explicacion: "La Estenosis Carotídea Ateroesclerótica es responsable de cerca del 15-20% de los accidentes cerebrovasculares isquémicos (ACV / AIT). Se considera 'Sintomática' cuando el paciente ha presentado síntomas neurológicos focales en el territorio carotídeo ipsilateral (AIT, amaurosis fugaz o ACV leve) dentro de los últimos 6 meses. La medición del porcentaje de estenosis se realiza mediante Eco-Doppler carotídeo o Angio-TAC. En pacientes sintomáticos con estenosis severa (70-99%), el tratamiento de elección para reducir drásticamente la recurrencia de ACV es la Endarterectomía Carotídea quirúrgica realizada precozmente (idealmente dentro de los primeros 14 días del evento sintomático) asociada a tratamiento médico óptimo."
  },
  44: {
    vignette: "Mujer de 52 años, cursando 5° día postoperatorio de reemplazo total de cadera, presenta aumento de volumen doloroso en la extremidad inferior izquierda, con eritema, calor local y empastamiento muscular en la pantorrilla. El signo de Homans es positivo y la diferencia de diámetro de pantorrilla respecto a la derecha es de 4.5 cm.",
    explicacion: "La Trombosis Venosa Profunda (TVP) de extremidades inferiores forma parte del tromboembolismo venoso y se desencadena por los factores de la Tríada de Virchow: estasis venosa, hipercoagulabilidad y daño endotelial. La estratificación del riesgo clínico se realiza mediante la Escala de Wells para TVP. En pacientes con riesgo alto (Wells ≥ 2), el examen confirmatorio de elección es el Eco-Doppler Venoso de Extremidades Inferiores. El tratamiento farmacológico inmediato es la Anticoagulación Oral o Parenteral (DOACs de primera elección: Rivaroxabán o Apixabán) mantenida por un periodo mínimo de 3 meses para prevenir la extensión del trombo y la embolización pulmonar."
  },
  45: {
    vignette: "Mujer de 35 años, usuaria de anticonceptivos orales combinados, consulta por inicio súbito de disnea de esfuerzo y dolor torácico de tipo pleurítico en hemitórax derecho. Al examen: FC 115 lpm, saturación de O₂ 92% a aire ambiental, pulmones limpios. El ECG muestra taquicardia sinusal. El Angio-TAC de tórax confirma defecto de rellenado en la arteria lobar inferior derecha.",
    explicacion: "El Tromboembolismo Pulmonar (TEP) ocurre cuando un trombo venoso (procedente en >90% de las venas profundas de EEII) se desprende e impacta en la vasculatura arterial pulmonar. El síntoma más frecuente es la disnea de aparición brusca, seguida de dolor pleurítico y taquicardia. En pacientes hemodinámicamente estables con probabilidad clínica alta (Wells > 4), el examen confirmatorio de primera línea es la Angiotomografía Computada de Arterias Pulmonares (Angio-TAC de tórax). En pacientes con probabilidad baja/intermedia, el D-Dímero se utiliza por su alto valor predictivo negativo para descartar la patología. El pilar del tratamiento en TEP estable es la Anticoagulación rápida mantenida por al menos 3 a 6 meses."
  },
  46: {
    vignette: "Hombre de 58 años, en reposo prolongado por fractura de fémur, presenta bruscamente disnea extrema, cianosis, síncope y colapso circulatorio. Ingresa a Urgencias con PA 65/40 mmHg, FC 135 lpm, yugulares ingurgitadas y saturación 80%. El ecocardiograma de urgencia muestra dilatación aguda e hipocinesia del ventrículo derecho (signo de McConnell) con sobrecarga de presión.",
    explicacion: "El Tromboembolismo Pulmonar Masivo (TEP de alto riesgo) se define por la presencia de TEP acompañado de Inestabilidad Hemodinámica (hipotensión arterial persistente con PAS < 90 mmHg o caída PAS ≥ 40 mmHg durante más de 15 minutos no provocada por otra causa). La oclusión masiva del lecho vascular pulmonar genera falla ventricular derecha aguda y colapso del gasto cardíaco. La conducta terapéutica prioritaria e inmediata de rescate en el TEP Masivo con shock es la Terapia Trombolítica Sistémica con tPA (Alteplasa 100 mg EV infundidos en 2 horas), siempre que no existan contraindicaciones hemorrágicas absolutas, seguida de anticoagulación continua con Heparina No Fraccionada."
  },
  47: {
    vignette: "Mujer de 48 años consulta por pesadez, cansancio y prurito en ambas piernas que empeora al estar de pie durante su jornada laboral y mejora al elevar las extremidades. Al examen físico en bipedestación se aprecian telangiectasias, venas varicosas tortuosas y dilatadas en trayecto de vena safena magna, con hiperpigmentación ocrácea en el tercio distal del tobillo.",
    explicacion: "La Insuficiencia Venosa Crónica de Extremidades Inferiores es el trastorno vascular periférico más frecuente en la práctica médica. Se debe a la incompetencia valvular venosa y/o hipertensión venosa persistente. Los síntomas incluyen pesadez, dolor sordo y edema declive que empeoran al final del día. La clasificación clínica se realiza según el sistema CEAP (C0 a C6, siendo C2 varices, C4 cambios cutáneos pigmentarios y C6 úlcera venosa activa). El examen diagnóstico de elección para mapeo venoso es el Eco-Doppler venoso. El pilar del tratamiento conservador de primera línea es la Terapia de Compresión Elástica graduada (medias de compresión 20-30 mmHg) combinada con ejercicio de bomba muscular de pantorrilla y elevación de extremidades."
  }
};

console.log('Custom vignettes count:', Object.keys(customVignettesMap).length);
